AWSTemplateFormatVersion: '2010-09-09'
Description: 100DaysofCloud DynammoDB Tables
Resources:
  JourneyersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'Journeyers'
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
